name: InyakSimulator
version: Beta-0.0.1
main: com.ddang_.inyaksimulator.Inyaksimulator
authors: [ DDang_ ]
description: Minecraft inseangyaktal (life looting, like faction) main system for 1.12.2 bukkit server
website: https://github.com/I-am-ddang
depend:
  - Kotlin
commands:
  fix:
    description: Item fix command
  gm:
    description: gamemode change command
    permission: inyak.gm
  i:
    description: get player's info command
  s:
    description: tp target to me command
  setspawn:
    description: set spawn command
    permission: inyak.setspawn
  spawn:
    description: spawn command
  tp:
    description: tp to target command
    permission: inyak.tp
  warp:
    description: warp command
    permission: inyak.warp
  isreload:
    description: reload config command
    permission: inyak.isreload
  setwarp:
    description: setwarp command
    permission: inyak.setwarp
  lore:
    description: lore set command
    permission: inyak.lore